<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
'key' => 'group_617453942c7a7',
'title' => 'CB Artikel (Anweisungen für Autor*innen)',
'fields' => array(
array(
'key' => 'field_617453a2d5ebc',
'label' => 'Anweisungen für Autor*innen',
'name' => '',
'type' => 'message',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'message' => 'So werden neue Artikel erstellt:
1. Artikel Titel oben eingeben
2. Auf der rechten Seite die entsprechende Kategorie / die entsprechenden Kategorien für den Artikel auswählen
3. Auf der rechten Seite auch ein passendes Artikelbild wählen
4. Die Felder bearbeiten, alle Felder mit (*) sind Pflichfelder
5. Veröffentlichen und dazu passenden Zeitrahmen erstellen

BITTE KEINE BLOCKS HINZUFÜGEN (KANN DAS LEIDER NICHT DEAKTIVIEREN)',
'new_lines' => 'wpautop',
'esc_html' => 0,
),
),
'location' => array(
array(
array(
  'param' => 'post_type',
  'operator' => '==',
  'value' => 'cb_item',
),
),
),
'menu_order' => 0,
'position' => 'acf_after_title',
'style' => 'default',
'label_placement' => 'left',
'instruction_placement' => 'label',
'hide_on_screen' => array(
0 => 'the_content',
1 => 'excerpt',
),
'active' => true,
'description' => '',
'show_in_rest' => false,
'acfe_display_title' => '',
'acfe_autosync' => '',
'acfe_form' => 0,
'acfe_meta' => '',
'acfe_note' => '',
));

acf_add_local_field_group(array(
'key' => 'group_616d972244e05',
'title' => 'Freie Lasten Optionen',
'fields' => array(
array(
'key' => 'field_616d97272798d',
'label' => 'Kartenvorlage für Kategorienseite',
'name' => 'template_cat_map',
'type' => 'post_object',
'instructions' => 'Welche Vorlage für die Karte verwendet werden soll, die auf den jeweiligen Stadtseiten angezeigt wird',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'post_type' => array(
  0 => 'cb_map',
),
'taxonomy' => '',
'allow_null' => 0,
'multiple' => 0,
'return_format' => 'object',
'save_custom' => 0,
'save_post_status' => 'publish',
'acfe_bidirectional' => array(
  'acfe_bidirectional_enabled' => '0',
),
'ui' => 1,
),
array(
'key' => 'field_61744e706db69',
'label' => 'Bestätigungsbild für die Buchung',
'name' => 'booking_confirm',
'type' => 'image',
'instructions' => 'Wird als gif/Bild angezeigt neben dem Text zu der beendeten Buchung',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'uploader' => 'wp',
'acfe_thumbnail' => 0,
'return_format' => 'url',
'preview_size' => 'medium',
'library' => 'all',
'min_width' => '',
'min_height' => '',
'min_size' => '',
'max_width' => '',
'max_height' => '',
'max_size' => '',
'mime_types' => '',
),
array(
'key' => 'field_617fcc3f11eb6',
'label' => 'Verfügbarkeiten manuell aktualisieren',
'name' => 'update_bookablemeta',
'type' => 'acfe_button',
'instructions' => 'Aktualisiert den aktuellen Buchbarkeitsstatus von Artikeln (nur benutzen falls es automatisch nicht funktionieren sollte). Betrifft die Anzeige der Artikel im Menü, in den Portfolios und den Post-Grids.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'button_value' => 'Aktualisieren',
'button_type' => 'button',
'button_class' => 'button button-secondary',
'button_id' => '',
'button_before' => '',
'button_after' => '',
'button_ajax' => 1,
),
array(
'key' => 'field_61c889c024be1',
'label' => 'Seite für Weber Kupplung',
'name' => 'page_weber',
'type' => 'page_link',
'instructions' => 'Die Beschreibungsseite für die Weber Kupplung',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'post_type' => array(
  0 => 'page',
),
'taxonomy' => '',
'allow_null' => 0,
'allow_archives' => 1,
'multiple' => 0,
),
array(
'key' => 'field_61c889fa24be2',
'label' => 'Seite für Haerry Kupplung',
'name' => 'page_haerry',
'type' => 'page_link',
'instructions' => 'Die Beschreibungsseite für die Haerry Kupplung',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'post_type' => array(
  0 => 'page',
),
'taxonomy' => '',
'allow_null' => 0,
'allow_archives' => 1,
'multiple' => 0,
),
),
'location' => array(
array(
array(
  'param' => 'options_page',
  'operator' => '==',
  'value' => 'freielasten-settings',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'left',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => 0,
'acfe_display_title' => '',
'acfe_autosync' => '',
'acfe_form' => 0,
'acfe_meta' => '',
'acfe_note' => '',
));

acf_add_local_field_group(array(
'key' => 'group_60ed8f58771b1',
'title' => 'Hauptmenü',
'fields' => array(
array(
'key' => 'field_60ed92699a8f6',
'label' => 'Name Ausleihmenü',
'name' => 'name_ausleihmenu',
'type' => 'text',
'instructions' => 'Name des Menüpunkts für die Unterkategorien',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => 'Ausleihen',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
array(
'key' => 'field_60ed928c9a8f7',
'label' => 'Icon Ausleihemenue',
'name' => 'icon_ausleihemenue',
'type' => 'file',
'instructions' => 'Icon für das Ausleihemenü',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'uploader' => '',
'return_format' => 'array',
'min_size' => '',
'max_size' => '',
'mime_types' => 'svg',
'library' => 'all',
),
array(
'key' => 'field_60ed9364abded',
'label' => 'Dazugehörige Seite Ausleihmenü',
'name' => 'dazugehorige_seite_ausleihmenu',
'type' => 'page_link',
'instructions' => 'Zu welcher Seite zeigt das Ausleihmenü?',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'post_type' => array(
  0 => 'page',
),
'taxonomy' => '',
'allow_null' => 0,
'allow_archives' => 1,
'multiple' => 0,
),
array(
'key' => 'field_60ed900a8f743',
'label' => 'Kategorien für die Ausleihe',
'name' => 'kategorien_fur_die_ausleihe',
'type' => 'repeater',
'instructions' => 'Das sind die Kategorien die in dem Ausleihmenü angezeigt werden sollen.',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'acfe_repeater_stylised_button' => 0,
'collapsed' => '',
'min' => 1,
'max' => 0,
'layout' => 'table',
'button_label' => '',
'sub_fields' => array(
  array(
    'key' => 'field_60ed90428f744',
    'label' => 'Kategorie',
    'name' => 'kategorie',
    'type' => 'taxonomy',
    'instructions' => '',
    'required' => 1,
    'conditional_logic' => 0,
    'wrapper' => array(
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'taxonomy' => 'cb_items_category',
    'field_type' => 'radio',
    'allow_null' => 0,
    'add_term' => 0,
    'save_terms' => 0,
    'load_terms' => 0,
    'return_format' => 'id',
    'multiple' => 0,
  ),
  array(
    'key' => 'field_60ed91005897d',
    'label' => 'Icon',
    'name' => 'cat_ico',
    'type' => 'file',
    'instructions' => 'Bitte wählen ein passendes Icon für die Kategorie',
    'required' => 1,
    'conditional_logic' => 0,
    'wrapper' => array(
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'uploader' => '',
    'return_format' => 'array',
    'min_size' => '',
    'max_size' => '',
    'mime_types' => 'svg',
    'library' => 'all',
  ),
  array(
    'key' => 'field_60ed911b5897e',
    'label' => 'Name',
    'name' => 'cat_name',
    'type' => 'text',
    'instructions' => 'Bitte wähle einen passenden Namen für die Kategorie',
    'required' => 1,
    'conditional_logic' => 0,
    'wrapper' => array(
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'default_value' => '',
    'placeholder' => '',
    'prepend' => '',
    'append' => '',
    'maxlength' => '',
  ),
  array(
    'key' => 'field_60ed9333d7c64',
    'label' => 'Dazugehörige Seite',
    'name' => 'linkingpage',
    'type' => 'page_link',
    'instructions' => '',
    'required' => 1,
    'conditional_logic' => 0,
    'wrapper' => array(
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'post_type' => array(
      0 => 'page',
    ),
    'taxonomy' => '',
    'allow_null' => 0,
    'allow_archives' => 1,
    'multiple' => 0,
  ),
),
),
array(
'key' => 'field_60f3002440e91',
'label' => 'Nur buchbare Artikel anzeigen',
'name' => 'show_bookableonly',
'type' => 'true_false',
'instructions' => 'Definiert, ob in dem Menü auch nur die aktuell buchbaren Artikel angezeigt werden sollen.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'message' => '',
'default_value' => 1,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_60fd6ef8eb8af',
'label' => 'Farbe des Ausleihenmenüs',
'name' => 'menu_color',
'type' => 'color_picker',
'instructions' => 'Welche Farbe soll das Menü haben?',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'enable_opacity' => false,
'return_format' => 'string',
),
array(
'key' => 'field_61699f6c690f9',
'label' => 'Artikelstandort berücksichtigen',
'name' => 'artikelstandort_anzeigen',
'type' => 'true_false',
'instructions' => 'Teilt die Artikel nach Standort nochmal auf',
'required' => 0,
'conditional_logic' => array(
  array(
    array(
      'field' => 'field_60f3002440e91',
      'operator' => '==',
      'value' => '1',
    ),
  ),
),
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'message' => '',
'default_value' => 0,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_61699fc6690fa',
'label' => 'Standortkategorien fuer das menu',
'name' => 'standortkategorien',
'type' => 'repeater',
'instructions' => '',
'required' => 1,
'conditional_logic' => array(
  array(
    array(
      'field' => 'field_61699f6c690f9',
      'operator' => '==',
      'value' => '1',
    ),
  ),
),
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'acfe_repeater_stylised_button' => 0,
'collapsed' => '',
'min' => 1,
'max' => 0,
'layout' => 'table',
'button_label' => '',
'sub_fields' => array(
  array(
    'key' => 'field_6169a010690fb',
    'label' => 'Standort Kategorie',
    'name' => 'standort_cat',
    'type' => 'taxonomy',
    'instructions' => 'Füge hier die Standard Kategorien zu nach denen die Artikel aufgeteilt werden',
    'required' => 1,
    'conditional_logic' => 0,
    'wrapper' => array(
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'taxonomy' => 'cb_locations_category',
    'field_type' => 'radio',
    'allow_null' => 0,
    'add_term' => 0,
    'save_terms' => 0,
    'load_terms' => 0,
    'return_format' => 'id',
    'acfe_bidirectional' => array(
      'acfe_bidirectional_enabled' => '0',
    ),
    'multiple' => 0,
  ),
  array(
    'key' => 'field_6169a085690fc',
    'label' => 'Standort Icon',
    'name' => 'standort_icon',
    'type' => 'font-awesome',
    'instructions' => 'Bitte wähle ein passendes Icon für die Standortkategorie (z.B. eine Stadt oder ein Haus)',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'icon_sets' => array(
      0 => 'fas',
      1 => 'far',
    ),
    'custom_icon_set' => '',
    'default_label' => '&lt;i class="fas"&gt;&amp;#xf64f;&lt;/i&gt; city',
    'default_value' => 'fas fa-city',
    'save_format' => 'element',
    'allow_null' => 0,
    'show_preview' => 1,
    'enqueue_fa' => 0,
    'fa_live_preview' => '',
    'choices' => array(
    ),
  ),
),
),
array(
'key' => 'field_6169a187690ff',
'label' => 'Fallback Standort',
'name' => 'fallback_standort',
'type' => 'text',
'instructions' => 'Falls einem Standort keine Kategorie zugewiesen sein sollte, wie soll dann das Feld heißen in das er einsortiert wird?',
'required' => 1,
'conditional_logic' => array(
  array(
    array(
      'field' => 'field_61699f6c690f9',
      'operator' => '==',
      'value' => '1',
    ),
  ),
),
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => 'Andere',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
),
'location' => array(
array(
array(
  'param' => 'nav_menu',
  'operator' => '==',
  'value' => 'location/primary',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => false,
'acfe_display_title' => '',
'acfe_autosync' => '',
'acfe_form' => 0,
'acfe_meta' => '',
'acfe_note' => '',
));

acf_add_local_field_group(array(
'key' => 'group_611aac534f406',
'title' => 'Pagemeta',
'fields' => array(
array(
'key' => 'field_611aac5c4bb97',
'label' => 'Fa-Icon',
'name' => 'fa-icon',
'type' => 'font-awesome',
'instructions' => 'FontAwesome Icon für die Seite',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'icon_sets' => array(
  0 => 'far',
),
'custom_icon_set' => '',
'default_label' => '',
'default_value' => '',
'save_format' => 'element',
'allow_null' => 0,
'show_preview' => 1,
'enqueue_fa' => 0,
'fa_live_preview' => '',
'choices' => array(
),
),
array(
'key' => 'field_611aacb74bb98',
'label' => 'SVG Icon',
'name' => 'svg_icon',
'type' => 'file',
'instructions' => 'NUR wenn kein FontAwesome Icon gefunden wurde. Definiert Icon für Seite.',
'required' => 0,
'conditional_logic' => array(
  array(
    array(
      'operator' => '',
      'value' => '',
    ),
  ),
),
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'uploader' => '',
'return_format' => 'url',
'min_size' => '',
'max_size' => '',
'mime_types' => 'svg',
'library' => 'all',
),
),
'location' => array(
array(
array(
  'param' => 'page_template',
  'operator' => '==',
  'value' => 'default',
),
array(
  'param' => 'page_template',
  'operator' => '==',
  'value' => 'page-templates/template-pagebuilder-full-width.php',
),
array(
  'param' => 'page_template',
  'operator' => '==',
  'value' => 'editorplus-template.php',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'left',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => false,
'acfe_display_title' => '',
'acfe_autosync' => '',
'acfe_form' => 0,
'acfe_meta' => '',
'acfe_note' => '',
));

acf_add_local_field_group(array(
'key' => 'group_61a4fd618bbe8',
'title' => 'Stil Menüelemente',
'fields' => array(
array(
'key' => 'field_61a4fd8c23843',
'label' => 'Farbe des Menüelements',
'name' => 'color-menu_obj',
'type' => 'color_picker',
'instructions' => 'Wenn keine Farben angegeben wird wird automatisch die Farbe des übergeordneten Elements übernommen',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'enable_opacity' => 0,
'return_format' => 'string',
),
array(
'key' => 'field_61a507e64505d',
'label' => 'Icon des Menüelements',
'name' => 'icon-menu_obj',
'type' => 'font-awesome',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'icon_sets' => array(
  0 => 'fas',
  1 => 'far',
),
'custom_icon_set' => '',
'default_label' => '',
'default_value' => '',
'save_format' => 'class',
'allow_null' => 0,
'show_preview' => 1,
'enqueue_fa' => 0,
'fa_live_preview' => '',
'choices' => array(
),
),
),
'location' => array(
array(
array(
  'param' => 'nav_menu_item',
  'operator' => '==',
  'value' => 'all',
),
),
),
'menu_order' => 0,
'position' => 'side',
'style' => 'default',
'label_placement' => 'left',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => 0,
'acfe_display_title' => '',
'acfe_autosync' => '',
'acfe_form' => 0,
'acfe_meta' => '',
'acfe_note' => '',
));

acf_add_local_field_group(array(
'key' => 'group_60cb28f46e79a',
'title' => 'Anhänger',
'fields' => array(
array(
'key' => 'field_60cb28f470ad0',
'label' => 'Galerie',
'name' => 'galerie',
'type' => 'gallery',
'instructions' => 'Hier kommt eine Sammlung von Bildern mit / von dem Artikel hinein',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'return_format' => 'array',
'preview_size' => 'medium',
'insert' => 'append',
'library' => 'all',
'min' => '',
'max' => '',
'min_width' => '',
'min_height' => '',
'min_size' => '',
'max_width' => '',
'max_height' => '',
'max_size' => '',
'mime_types' => '',
),
array(
'key' => 'field_60f2fc9a7b4b0',
'label' => 'Icon',
'name' => 'icon',
'type' => 'file',
'instructions' => 'Wähle ein passendes Icon für den Artikel',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'uploader' => '',
'return_format' => 'url',
'min_size' => '',
'max_size' => '',
'mime_types' => 'svg',
'library' => 'all',
),
array(
'key' => 'field_60d48ceefbf65',
'label' => 'Kurzer Beschreibungstext',
'name' => 'anhaenger_desc',
'type' => 'text',
'instructions' => 'Kurze Beschreibung des Anhängers',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => 'Schwerlastanhänger für große Lasten',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
array(
'key' => 'field_60cb28f470f19',
'label' => 'Kupplung',
'name' => 'kupplungen',
'type' => 'checkbox',
'instructions' => 'Was wird benötigt um den Anhänger an einem Fahrrad zu betreiben?',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'choices' => array(
  'weber' => 'Weber-Kupplung',
  'haerry' => 'Haerry-Kupplung',
  'sensor' => 'Sensorset (Carla-Cargo)',
  'other' => 'Andere Kupplung (bitte angeben)',
),
'allow_custom' => 0,
'default_value' => array(
),
'layout' => 'vertical',
'toggle' => 0,
'return_format' => 'value',
'save_custom' => 0,
),
array(
'key' => 'field_60cb2a5ba747a',
'label' => 'Kupplungsname',
'name' => 'alt_kupplung',
'type' => 'text',
'instructions' => 'Bitte gib den Namen der Alternativkupplung ein',
'required' => 1,
'conditional_logic' => array(
  array(
    array(
      'field' => 'field_60cb28f470f19',
      'operator' => '==',
      'value' => 'other',
    ),
  ),
),
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
array(
'key' => 'field_60da38cc02079',
'label' => 'Zubehör?',
'name' => 'zubehoer',
'type' => 'post_object',
'instructions' => 'Welches Zubehör hat dieser Anhänger? Bitte liste hier <b>nicht</b> alles verfügbare Zubehör sondern nur das, was schon auf dem Anhänger ist oder einfach montiert werden kann.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'post_type' => '',
'taxonomy' => array(
  0 => 'cb_items_category:zubehoer',
),
'allow_null' => 0,
'multiple' => 1,
'return_format' => 'object',
'save_custom' => 0,
'save_post_status' => 'publish',
'acfe_bidirectional' => array(
  'acfe_bidirectional_enabled' => true,
  'acfe_bidirectional_related' => array(
    0 => 'field_60e33f2c8c88f',
  ),
),
'ui' => 1,
),
array(
'key' => 'field_611a6c092d0c5',
'label' => 'Zubehör Foto/Icon in Artikelgalerien einbinden?',
'name' => 'change_to_extra',
'type' => 'true_false',
'instructions' => 'Sol das Titelfoto und Icon des aktuellen Artikels durch das des Zubehörs ersetzet werden? (Wirkt sich auf gesamte Webseite aus).
Dadurch wird das alte Foto nicht überschrieben, der Artikel ist aber überall als fest mit dem Zubehör verbunden erkennbar.

NOCH NICHT IMPLEMENTIERT (Hat keine Funktion)',
'required' => 0,
'conditional_logic' => array(
  array(
    array(
      'field' => 'field_60da38cc02079',
      'operator' => '!=empty',
    ),
    array(
      'field' => 'field_60da38cc02079',
      'operator' => '<',
      'value' => '2',
    ),
  ),
),
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'message' => '',
'default_value' => 0,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_60e33cbd213d9',
'label' => 'Text Zubehör',
'name' => 'text_zubehor',
'type' => 'text',
'instructions' => 'Infotext zu dem Zubehör',
'required' => 0,
'conditional_logic' => array(
  array(
    array(
      'field' => 'field_60da38cc02079',
      'operator' => '!=empty',
    ),
  ),
),
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => 'Falls Rumpumpel nicht benötigt / gewünscht wird bitte rechtzeitig vorher Bescheid geben.',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
array(
'key' => 'field_60cb28f470b3d',
'label' => 'Elektrounterstützung Pedelec?',
'name' => 'elektrounterstuetzung',
'type' => 'true_false',
'instructions' => 'Hat der Anhänger eine elektrische Unterstützung im Pedelec Modus?',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'message' => '',
'default_value' => 0,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_60cb28f470b76',
'label' => 'Unterstützung bis (km/h) - Pedelec',
'name' => 'unterstutzung_bis_kmh',
'type' => 'number',
'instructions' => 'Bis wie viel km/h unterstützt der Anhänger im Pedelec Modus?',
'required' => 1,
'conditional_logic' => array(
  array(
    array(
      'field' => 'field_60cb28f470b3d',
      'operator' => '==',
      'value' => '1',
    ),
  ),
),
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => '',
'min' => '',
'max' => '',
'step' => '',
),
array(
'key' => 'field_60cb2aaba747b',
'label' => 'Handwagenbetrieb möglich?',
'name' => 'hwagen',
'type' => 'true_false',
'instructions' => 'Ist der Betrieb dieses Anhängers im Handwagenbetrieb möglich?',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'message' => '',
'default_value' => 0,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_60cb2ad0a747c',
'label' => 'Elektrischer Handwagen?',
'name' => 'hwagen_elektro',
'type' => 'true_false',
'instructions' => 'Bietet der Handwagen eine elektrische Unterstützung?',
'required' => 0,
'conditional_logic' => array(
  array(
    array(
      'field' => 'field_60cb2aaba747b',
      'operator' => '==',
      'value' => '1',
    ),
  ),
),
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'message' => '',
'default_value' => 0,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_60cb2b81ca04a',
'label' => 'Unterstützung bis (km/h) - Handwagen',
'name' => 'hwagen_unterstuetzungkmh',
'type' => 'number',
'instructions' => 'Bis wie viel km/h unterstützt der Anhänger im Handwagen Modus?',
'required' => 1,
'conditional_logic' => array(
  array(
    array(
      'field' => 'field_60cb2ad0a747c',
      'operator' => '==',
      'value' => '1',
    ),
  ),
),
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => '',
'min' => '',
'max' => '',
'step' => '',
),
array(
'key' => 'field_60cb28f470be4',
'label' => 'Zusätzlicher Infotext (bei Bedarf)',
'name' => 'extrainfo',
'type' => 'textarea',
'instructions' => 'Welche zusätzliche Info ist noch wichtig?',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => 'Eine Anhängerkupplung kann bei Bedarf ausgeliehen werden',
'maxlength' => '',
'rows' => '',
'new_lines' => '',
),
array(
'key' => 'field_60cb28f470c1a',
'label' => 'Maximalzuladung (kg)',
'name' => 'zuladung',
'type' => 'number',
'instructions' => 'Die Zuladung die der Anhänger an einem Rad erlaubt (nicht als Handwagen)',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => 150,
'prepend' => '',
'append' => 'kg',
'min' => '',
'max' => '',
'step' => '',
),
array(
'key' => 'field_60d063f4fa3ff',
'label' => 'Maximalzuladung (kg) (Handwagen)',
'name' => 'hwagen_zuladung',
'type' => 'number',
'instructions' => 'Die Zuladung die der Anhänger als Handwagen erlaubt',
'required' => 0,
'conditional_logic' => array(
  array(
    array(
      'field' => 'field_60cb2aaba747b',
      'operator' => '==',
      'value' => '1',
    ),
  ),
),
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => 200,
'prepend' => '',
'append' => 'kg',
'min' => '',
'max' => '',
'step' => '',
),
array(
'key' => 'field_60cb28f470c51',
'label' => 'Bereitgestellt von...',
'name' => 'bereitgestellt_von',
'type' => 'text',
'instructions' => 'Wer stellt das Rad bereit?',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => 'FREIE Räder e.V.',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
array(
'key' => 'field_60d0691fcaa9f',
'label' => 'Redmine Link',
'name' => 'redmine_link',
'type' => 'url',
'instructions' => 'Link zur Wiki Seite des Artikels',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => '',
),
array(
'key' => 'field_60cb28f470c88',
'label' => 'Technische Infos',
'name' => '',
'type' => 'accordion',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'open' => 0,
'multi_expand' => 0,
'endpoint' => 0,
),
array(
'key' => 'field_60cb28f470cbe',
'label' => 'Motortyp',
'name' => 'motortyp',
'type' => 'text',
'instructions' => 'Art des Motors',
'required' => 0,
'conditional_logic' => array(
  array(
    array(
      'field' => 'field_60cb28f470b3d',
      'operator' => '==',
      'value' => '1',
    ),
  ),
  array(
    array(
      'field' => 'field_60cb2ad0a747c',
      'operator' => '==',
      'value' => '1',
    ),
  ),
),
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => 'Brushless Direct Drive Motor',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
array(
'key' => 'field_60cb28f470cf4',
'label' => 'Akkugröße (Wh)',
'name' => 'akkugroesse',
'type' => 'number',
'instructions' => 'Die Größe des Akkus in Wattstunden, wenn unbekannt einfach leerlassen',
'required' => 0,
'conditional_logic' => array(
  array(
    array(
      'field' => 'field_60cb28f470b3d',
      'operator' => '==',
      'value' => '1',
    ),
  ),
  array(
    array(
      'field' => 'field_60cb2ad0a747c',
      'operator' => '==',
      'value' => '1',
    ),
  ),
),
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => 1400,
'prepend' => '',
'append' => 'wH',
'min' => '',
'max' => '',
'step' => '',
),
array(
'key' => 'field_60d064abfa402',
'label' => 'Reichweite',
'name' => 'reichweite',
'type' => 'text',
'instructions' => 'Die Reichweite des Akkus in km',
'required' => 0,
'conditional_logic' => array(
  array(
    array(
      'field' => 'field_60cb28f470b3d',
      'operator' => '==',
      'value' => '1',
    ),
  ),
  array(
    array(
      'field' => 'field_60cb2ad0a747c',
      'operator' => '==',
      'value' => '1',
    ),
  ),
),
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => 'km',
'maxlength' => '',
),
array(
'key' => 'field_60d06609fa404',
'label' => 'Bremsen',
'name' => 'bremsen',
'type' => 'textarea',
'instructions' => 'Art der Bremsen (mehrere Zeilen bei mehreren Bremsen)',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => 'Auflaufbremse mit Scheibenbremsen',
'maxlength' => '',
'rows' => '',
'new_lines' => '',
),
array(
'key' => 'field_60cb28f470d61',
'label' => 'Leergewicht (kg)',
'name' => 'leergewicht',
'type' => 'number',
'instructions' => 'Leergewicht des Anhängers (in KG)',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => 40,
'prepend' => '',
'append' => 'kg',
'min' => '',
'max' => '',
'step' => '',
),
array(
'key' => 'field_60cb28f470e39',
'label' => 'Länge Anhänger (cm)',
'name' => 'laenge_fahrzeug',
'type' => 'number',
'instructions' => 'Die Minimallänge des Fahrzeuges (bei Anhänger mit Deichsel den Wert mit eingedrehter Deichsel)',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => 'cm',
'min' => '',
'max' => '',
'step' => 0,
),
array(
'key' => 'field_60cb28f470e03',
'label' => 'Breite Anhänger (cm)',
'name' => 'breite_fahrzeug',
'type' => 'number',
'instructions' => 'Breite des Anhängers (in cm)',
'required' => 1,
'conditional_logic' => array(
  array(
    array(
      'field' => 'field_60cb28f470e39',
      'operator' => '!=empty',
    ),
  ),
),
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => 95,
'placeholder' => '',
'prepend' => '',
'append' => 'cm',
'min' => '',
'max' => '',
'step' => '',
),
array(
'key' => 'field_60d06738c6073',
'label' => 'Länge Ladefläche (cm)',
'name' => 'ladeflaeche_laenge',
'type' => 'number',
'instructions' => 'Die Länge der Ladefläche des Anhängers (in cm)',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => 'cm',
'min' => '',
'max' => '',
'step' => 0,
),
array(
'key' => 'field_60d06772c6074',
'label' => 'Breite Ladefläche (cm)',
'name' => 'ladeflaeche_breite',
'type' => 'number',
'instructions' => 'Die Breite der Ladefläche des Anhängers (in cm)',
'required' => 1,
'conditional_logic' => array(
  array(
    array(
      'field' => 'field_60d06738c6073',
      'operator' => '!=empty',
    ),
  ),
),
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => 'cm',
'min' => '',
'max' => '',
'step' => 0,
),
array(
'key' => 'field_60cb28f470e6f',
'label' => 'Sondertext Maße',
'name' => 'stext_masse',
'type' => 'textarea',
'instructions' => 'Zusatzinfo (zb. zur Deichsel)',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => 'ohne Deichsel 235 cm mit Deichsel 300 cm',
'maxlength' => '',
'rows' => '',
'new_lines' => '',
'acfe_textarea_code' => 0,
),
array(
'key' => 'field_60cb28f470eac',
'label' => 'Ladevolumen (m³)',
'name' => 'ladevolumen',
'type' => 'number',
'instructions' => 'Das Ladevolumen in m³',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => '',
'min' => '',
'max' => '',
'step' => '',
),
array(
'key' => 'field_60d06833caa9e',
'label' => 'Sondertext Zuladung',
'name' => 'stext_zuladung',
'type' => 'textarea',
'instructions' => 'Zusatzinfo zur Zuladung (z.B. Kompatibilität mit Euro Kisten)',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => 'Für Kisten im Euronorm Format',
'maxlength' => '',
'rows' => '',
'new_lines' => '',
),
array(
'key' => 'field_60da46ae257e7',
'label' => 'Modellname',
'name' => 'modellname',
'type' => 'text',
'instructions' => 'Was ist der Name des Anhängermodells? Von welcher Marke ist er?',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
),
'location' => array(
array(
array(
  'param' => 'post_type',
  'operator' => '==',
  'value' => 'cb_item',
),
array(
  'param' => 'post_taxonomy',
  'operator' => '==',
  'value' => 'cb_items_category:anhaenger',
),
),
),
'menu_order' => 1,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => false,
'acfe_display_title' => '',
'acfe_autosync' => '',
'acfe_form' => 0,
'acfe_meta' => '',
'acfe_note' => '',
));

acf_add_local_field_group(array(
'key' => 'group_611a6dedd178b',
'title' => 'Inklusionsrad',
'fields' => array(
array(
'key' => 'field_611a6dedd75bc',
'label' => 'Galerie',
'name' => 'galerie',
'type' => 'gallery',
'instructions' => 'Hier kommt eine Sammlung von Bildern mit / von dem Artikel hinein',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'return_format' => 'array',
'preview_size' => 'medium',
'insert' => 'append',
'library' => 'all',
'min' => '',
'max' => '',
'min_width' => '',
'min_height' => '',
'min_size' => '',
'max_width' => '',
'max_height' => '',
'max_size' => '',
'mime_types' => '',
),
array(
'key' => 'field_611a6dedd75f5',
'label' => 'Beschreibungstext',
'name' => 'inklusion_desc',
'type' => 'wysiwyg',
'instructions' => 'Beschreibung des Inklusionsrades',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'tabs' => 'all',
'toolbar' => 'full',
'media_upload' => 1,
'delay' => 0,
),
array(
'key' => 'field_611a6dedd7661',
'label' => 'Icon',
'name' => 'icon',
'type' => 'file',
'instructions' => '',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'uploader' => '',
'return_format' => 'url',
'min_size' => '',
'max_size' => '',
'mime_types' => 'svg',
'library' => 'all',
),
),
'location' => array(
array(
array(
  'param' => 'post_type',
  'operator' => '==',
  'value' => 'cb_item',
),
array(
  'param' => 'post_taxonomy',
  'operator' => '==',
  'value' => 'cb_items_category:inklusion',
),
),
),
'menu_order' => 1,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => false,
'acfe_display_title' => '',
'acfe_autosync' => '',
'acfe_form' => 0,
'acfe_meta' => '',
'acfe_note' => '',
));

acf_add_local_field_group(array(
'key' => 'group_60ba3fa474a4b',
'title' => 'Lastenfahrrad',
'fields' => array(
array(
'key' => 'field_60bf21a7b3e5b',
'label' => 'Galerie',
'name' => 'galerie',
'type' => 'gallery',
'instructions' => 'Hier kommt eine Sammlung von Bildern mit / von dem Artikel hinein. Bitte nicht das Artikelbild zweimal verwenden! (Nur zusätzliche Bilder aus anderen Perspektiven)',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'return_format' => 'array',
'preview_size' => 'medium',
'insert' => 'append',
'library' => 'all',
'min' => '',
'max' => '',
'min_width' => '',
'min_height' => '',
'min_size' => '',
'max_width' => '',
'max_height' => '',
'max_size' => '',
'mime_types' => '',
),
array(
'key' => 'field_60eb2ebcd5522',
'label' => 'Icon',
'name' => 'icon',
'type' => 'file',
'instructions' => 'Wähle ein passendes Icon für den Artikel',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'return_format' => 'url',
'library' => 'all',
'min_size' => '',
'max_size' => '',
'mime_types' => 'svg',
),
array(
'key' => 'field_60bf226b449d4',
'label' => 'Spuren',
'name' => 'spuren',
'type' => 'select',
'instructions' => 'Ist das Fahrrad zwei- oder dreispurig?',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'choices' => array(
  'zweirad' => 'Zweirad',
  'dreirad' => 'Dreirad',
),
'default_value' => false,
'allow_null' => 0,
'multiple' => 0,
'ui' => 0,
'return_format' => 'value',
'ajax' => 0,
'placeholder' => '',
),
array(
'key' => 'field_60bf2204b3e5c',
'label' => 'Elektrounterstützung?',
'name' => 'elektrounterstuetzung',
'type' => 'true_false',
'instructions' => 'Hat das Fahrrad eine elektrische Unterstützung?',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'message' => '',
'default_value' => 0,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_60bf28b3886bb',
'label' => 'Unterstützung bis (km/h)',
'name' => 'unterstutzung_bis_kmh',
'type' => 'text',
'instructions' => '',
'required' => 1,
'conditional_logic' => array(
  array(
    array(
      'field' => 'field_60bf2204b3e5c',
      'operator' => '==',
      'value' => '1',
    ),
  ),
),
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => 25,
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
array(
'key' => 'field_60ba44caaf4b8',
'label' => 'Besonderheiten',
'name' => 'besonderheiten',
'type' => 'text',
'instructions' => 'Was macht das Fahrrad herausfordernd(er) zu fahren?',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => 'Indirekte Lenkung',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
array(
'key' => 'field_60ba4511af4b9',
'label' => 'Was sollte ich vor der Buchung wissen?',
'name' => 'extrainfo',
'type' => 'textarea',
'instructions' => 'Was sollten Nutzende wissen, bevor Sie das Rad buchen?',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => 'Das Rad fährt sich anders als dein Rad!
Bitte probefahren!',
'placeholder' => '',
'maxlength' => '',
'rows' => '',
'new_lines' => '',
),
array(
'key' => 'field_60ba3feeaf4b5',
'label' => 'Zuladung (kg)',
'name' => 'zuladung',
'type' => 'number',
'instructions' => 'Die Zuladung die das Rad erlaubt (ohne Fahrende Person also nicht die Gesamtzuladung)',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => 80,
'placeholder' => '00',
'prepend' => '',
'append' => 'kg',
'min' => '',
'max' => '',
'step' => '',
),
array(
'key' => 'field_61cafd24be8d0',
'label' => 'Maximale Belastung',
'name' => 'gesamtbelastung',
'type' => 'number',
'instructions' => 'Das zulässige Gesamtgewicht des Rades mit fahrender Person.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => '00',
'prepend' => '',
'append' => 'kg',
'min' => '',
'max' => '',
'step' => '',
),
array(
'key' => 'field_60bf8d8b3c77c',
'label' => 'Bereitgestellt von...',
'name' => 'bereitgestellt_von',
'type' => 'text',
'instructions' => 'Wer stellt das Rad bereit?',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => 'FREIE Räder e.V.',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
array(
'key' => 'field_60d068b17828b',
'label' => 'Link zum Redmine',
'name' => 'redmine_link',
'type' => 'url',
'instructions' => 'Den Link zur Wiki Seite des Artikels',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => '',
),
array(
'key' => 'field_60c4c52713fdf',
'label' => 'Technische Infos',
'name' => '',
'type' => 'accordion',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'open' => 1,
'multi_expand' => 1,
'endpoint' => 0,
),
array(
'key' => 'field_60bf2431449dc',
'label' => 'Motortyp',
'name' => 'motortyp',
'type' => 'text',
'instructions' => 'Art des Motors',
'required' => 0,
'conditional_logic' => array(
  array(
    array(
      'field' => 'field_60bf2204b3e5c',
      'operator' => '==',
      'value' => '1',
    ),
  ),
),
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => 'Shimano Steps E8000',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
array(
'key' => 'field_60d064bf001a0',
'label' => 'Reichweite (km)',
'name' => 'reichweite',
'type' => 'text',
'instructions' => 'Die ungefähre Reichweite des Fahrrads mit voll geladenem Akku (in km)',
'required' => 0,
'conditional_logic' => array(
  array(
    array(
      'field' => 'field_60bf2204b3e5c',
      'operator' => '==',
      'value' => '1',
    ),
  ),
),
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => 40,
'prepend' => '',
'append' => 'km',
'maxlength' => '',
),
array(
'key' => 'field_60bf2505449de',
'label' => 'Akkugröße (Wh)',
'name' => 'akkugroesse',
'type' => 'number',
'instructions' => 'Die Größe des Akkus in Wattstunden, wenn unbekannt einfach leerlassen',
'required' => 0,
'conditional_logic' => array(
  array(
    array(
      'field' => 'field_60bf2204b3e5c',
      'operator' => '==',
      'value' => '1',
    ),
  ),
),
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => 500,
'prepend' => '',
'append' => 'wH',
'min' => '',
'max' => '',
'step' => '',
),
array(
'key' => 'field_617fca398e3da',
'label' => 'Ersatzakkus?',
'name' => 'ersatzakkus',
'type' => 'number',
'instructions' => 'Wie viele Ersatzakkus sind verfügbar?',
'required' => 0,
'conditional_logic' => array(
  array(
    array(
      'field' => 'field_60bf2204b3e5c',
      'operator' => '==',
      'value' => '1',
    ),
  ),
),
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => 2,
'prepend' => '',
'append' => '',
'min' => '',
'max' => '',
'step' => '',
),
array(
'key' => 'field_60ba447eaf4b7',
'label' => 'Schaltungstyp',
'name' => 'schaltung',
'type' => 'text',
'instructions' => 'Typ der Schaltung',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => '14 Gang Nabenschaltung (Rohloff)',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
array(
'key' => 'field_60bf2398449da',
'label' => 'Leergewicht (kg)',
'name' => 'leergewicht',
'type' => 'number',
'instructions' => 'Leergewicht des Fahrrads (in KG)',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => 36,
'prepend' => '',
'append' => 'kg',
'min' => '',
'max' => '',
'step' => '',
),
array(
'key' => 'field_60bf236c449d8',
'label' => 'Sattelstange verstellbar?',
'name' => 'sattelstange_verstellbar',
'type' => 'true_false',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'message' => '',
'default_value' => 0,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_60bf2389449d9',
'label' => 'Lenkerstange verstellbar?',
'name' => 'lenkerstange_verstellbar',
'type' => 'true_false',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'message' => '',
'default_value' => 0,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_60bf22ae449d5',
'label' => 'Breite (cm)',
'name' => 'breite_velo',
'type' => 'number',
'instructions' => 'Breite des Fahrrads',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => 'cm',
'min' => '',
'max' => '',
'step' => '',
),
array(
'key' => 'field_60bf22d4449d6',
'label' => 'Länge (cm)',
'name' => 'laenge_velo',
'type' => 'number',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => 'cm',
'min' => '',
'max' => '',
'step' => 0,
),
array(
'key' => 'field_60bf22e2449d7',
'label' => 'Sondertext Maße',
'name' => 'stext_masse',
'type' => 'text',
'instructions' => 'Meistens die Info, ob ein Fahrrad in den Aufzug beim Bahnhof passt',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => 'Passt so gerade diagonal in den Aufzug am Haupt-Bhf',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
array(
'key' => 'field_60bf23ba449db',
'label' => 'Ladefläche (Text)',
'name' => 'ladeflache',
'type' => 'textarea',
'instructions' => 'Ein kleiner Text zu den Maßen der Ladefläche',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => 'Länge: 60 cm (unten) – 82,4 cm (oben)
Breite: 46,6 cm',
'placeholder' => '',
'maxlength' => '',
'rows' => '',
'new_lines' => '',
'acfe_textarea_code' => 0,
),
array(
'key' => 'field_61549eedb3833',
'label' => 'Modell',
'name' => 'modell',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'placeholder' => 'Larry vs. Harry Bullitt',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
array(
'key' => 'field_60c4c5e7e0fbb',
'label' => 'Kompatibilität',
'name' => '',
'type' => 'accordion',
'instructions' => 'Welche technischen Merkmale hat das Fahrrad, mit was ist es damit kompatibel?',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'open' => 1,
'multi_expand' => 1,
'endpoint' => 0,
),
array(
'key' => 'field_60bf2473449dd',
'label' => 'Kupplungen + Extras',
'name' => 'kupplungen',
'type' => 'checkbox',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'choices' => array(
  'haerry' => 'Haerry-Kupplung',
  'weber' => 'Weber-Kupplung',
  'kindersitz' => 'Kindersitz',
  'gepaecktraeger' => 'Gepäckträger',
  'tbox' => 'Transportbox',
  'tkiste' => 'Transportkiste',
  'tkisteverdeck' => 'Transportkiste mit Regenverdeck',
),
'allow_custom' => 0,
'default_value' => array(
),
'layout' => 'vertical',
'toggle' => 0,
'return_format' => 'value',
'save_custom' => 0,
),
),
'location' => array(
array(
array(
  'param' => 'post_type',
  'operator' => '==',
  'value' => 'cb_item',
),
array(
  'param' => 'post_taxonomy',
  'operator' => '==',
  'value' => 'cb_items_category:lastenrad',
),
),
),
'menu_order' => 1,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => 0,
'acfe_display_title' => '',
'acfe_autosync' => '',
'acfe_form' => 0,
'acfe_meta' => '',
'acfe_note' => '',
));

acf_add_local_field_group(array(
'key' => 'group_60e33e336df0f',
'title' => 'Zubehör',
'fields' => array(
array(
'key' => 'field_60e33e6c8c88d',
'label' => 'Galerie',
'name' => 'galerie',
'type' => 'gallery',
'instructions' => 'Hier kommt eine Sammlung von Bildern mit / von dem Artikel hinein',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'return_format' => 'array',
'preview_size' => 'medium',
'insert' => 'append',
'library' => 'all',
'min' => '',
'max' => '',
'min_width' => '',
'min_height' => '',
'min_size' => '',
'max_width' => '',
'max_height' => '',
'max_size' => '',
'mime_types' => '',
),
array(
'key' => 'field_60e33eb98c88e',
'label' => 'Beschreibungstext',
'name' => 'zubehoer_desc',
'type' => 'wysiwyg',
'instructions' => 'Beschreibung des Zubehörs',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'default_value' => '',
'tabs' => 'all',
'toolbar' => 'full',
'media_upload' => 1,
'delay' => 0,
),
array(
'key' => 'field_60e33f2c8c88f',
'label' => 'Verbunden mit',
'name' => 'attached_to',
'type' => 'post_object',
'instructions' => 'Mit welchem Artikel ist dieses Zubehör fest verbunden?',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'post_type' => array(
  0 => 'cb_item',
),
'taxonomy' => '',
'allow_null' => 0,
'multiple' => 1,
'return_format' => 'object',
'save_custom' => 0,
'save_post_status' => 'publish',
'acfe_bidirectional' => array(
  'acfe_bidirectional_enabled' => '1',
  'acfe_bidirectional_related' => array(
    0 => 'field_60da38cc02079',
  ),
),
'ui' => 1,
),
array(
'key' => 'field_611a6db8dd17c',
'label' => 'Icon',
'name' => 'icon',
'type' => 'file',
'instructions' => '',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'uploader' => '',
'return_format' => 'url',
'min_size' => '',
'max_size' => '',
'mime_types' => 'svg',
'library' => 'all',
),
array(
'key' => 'field_6176e810e2fbc',
'label' => 'Kompatibel mit',
'name' => 'kompatibel_mit',
'type' => 'post_object',
'instructions' => 'Mit welchem Artikel ist dieses Zubehör kompatibel? Bitte nur eintragen, wenn es leicht zu verbauen ist und nicht wenn es fest verbaut ist.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
  'width' => '',
  'class' => '',
  'id' => '',
),
'post_type' => array(
  0 => 'cb_item',
),
'taxonomy' => '',
'allow_null' => 0,
'multiple' => 1,
'return_format' => 'object',
'save_custom' => 0,
'save_post_status' => 'publish',
'acfe_bidirectional' => array(
  'acfe_bidirectional_enabled' => '0',
),
'ui' => 1,
),
),
'location' => array(
array(
array(
  'param' => 'post_type',
  'operator' => '==',
  'value' => 'cb_item',
),
array(
  'param' => 'post_taxonomy',
  'operator' => '==',
  'value' => 'cb_items_category:zubehoer',
),
),
),
'menu_order' => 1,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => false,
'acfe_display_title' => '',
'acfe_autosync' => '',
'acfe_form' => 0,
'acfe_meta' => '',
'acfe_note' => '',
));

endif;				
?>
